ALTER TABLE "University" ADD COLUMN IF NOT EXISTS ranking INTEGER;
ALTER TABLE "University" ADD COLUMN IF NOT EXISTS "customFields" JSONB DEFAULT '{}';
ALTER TABLE "University" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT now();
