import type {
  AuditEntry,
  DocumentRecord,
  Lead,
  Organization,
  Payment,
  Student,
  UserRecord,
} from "./types";

const day = (n: number) => {
  const d = new Date();
  d.setHours(12, 0, 0, 0);
  d.setDate(d.getDate() + n);
  return d;
};

export const firm: Organization = {
  id: "f1",
  name: "Center for Higher Studies",
  kind: "firm",
  path: "org.chs",
  parentId: null,
  seatsUsed: 13,
  seatsBilled: 30,
};

export const agencies: Organization[] = [
  {
    id: "ag1",
    name: "Dhaka Central",
    kind: "agency",
    path: "org.chs.dhaka",
    parentId: "f1",
    city: "Dhaka",
    managerName: "Tanvir Ahmed",
    seatsUsed: 6,
    seatsBilled: 10,
  },
  {
    id: "ag2",
    name: "Chattogram Branch",
    kind: "agency",
    path: "org.chs.ctg",
    parentId: "f1",
    city: "Chattogram",
    managerName: "Farhana Akter",
    seatsUsed: 4,
    seatsBilled: 10,
  },
  {
    id: "ag3",
    name: "Sylhet Desk",
    kind: "agency",
    path: "org.chs.sylhet",
    parentId: "f1",
    city: "Sylhet",
    managerName: "Kamrul Islam",
    seatsUsed: 3,
    seatsBilled: 10,
  },
];

export const users: UserRecord[] = [
  {
    id: "u1",
    name: "Nusrat Jahan",
    email: "nusrat@chs.edu.bd",
    role: "counsellor",
    orgId: "ag1",
    status: "active",
  },
  {
    id: "u2",
    name: "Tanvir Ahmed",
    email: "tanvir@chs.edu.bd",
    role: "agency_manager",
    orgId: "ag1",
    status: "active",
  },
  {
    id: "u3",
    name: "Sabbir Khan",
    email: "sabbir@chs.edu.bd",
    role: "counsellor",
    orgId: "ag1",
    status: "active",
  },
  {
    id: "u4",
    name: "Farhana Akter",
    email: "farhana@chs.edu.bd",
    role: "agency_manager",
    orgId: "ag2",
    status: "active",
  },
  {
    id: "u5",
    name: "Mehedi Hasan",
    email: "mehedi@chs.edu.bd",
    role: "counsellor",
    orgId: "ag2",
    status: "invited",
  },
  {
    id: "u6",
    name: "Kamrul Islam",
    email: "kamrul@sylhetstudylink.com",
    role: "agent",
    orgId: "ag3",
    status: "active",
  },
];

const pipeline = (
  names: string[],
  doneCount: number,
): Student["stages"] =>
  names.map((name, i) => ({
    id: `st-${name}-${i}`,
    name,
    done: i < doneCount,
    due: day(i < doneCount ? -(doneCount - i) * 7 : (i - doneCount) * 9 + 3),
  }));

const cyprusStages = [
  "Counselling session",
  "Documents collected",
  "Application submitted",
  "Offer letter received",
  "Tuition deposit paid",
  "Visa file prepared",
  "Visa interview",
  "Visa decision",
  "Pre-departure briefing",
  "Arrived",
];

const ukStages = [
  "Counselling session",
  "Documents collected",
  "English test",
  "Application submitted",
  "Conditional offer",
  "Unconditional offer and deposit",
  "CAS issued",
  "Biometrics",
  "Visa decision",
  "Arrived",
];

function docs(names: string[], approved: number): Student["docs"] {
  return names.map((name, i) => ({
    id: `d-${name}-${i}`,
    name,
    status: i < approved ? "approved" : i === approved ? "uploaded" : "missing",
  }));
}

export const students: Student[] = [
  {
    id: "s1",
    name: "Ayesha Siddiqua",
    email: "ayesha.siddiqua1@gmail.com",
    phone: "+880 1711-204518",
    orgId: "ag1",
    counsellorId: "u1",
    agentId: null,
    country: "Cyprus",
    university: "UCLan Cyprus",
    programme: "BSc Computer Science",
    intake: "Fall 2026",
    status: "active",
    stages: pipeline(cyprusStages, 5),
    docs: docs(
      [
        "Academic documents",
        "English certificate",
        "Passport copy",
        "Police clearance",
        "Bank statement",
        "Sponsor letter",
        "SWIFT copy",
      ],
      4,
    ),
  },
  {
    id: "s2",
    name: "Rafi Ahmed",
    email: "rafi.ahmed2@gmail.com",
    phone: "+880 1712-338104",
    orgId: "ag1",
    counsellorId: "u1",
    agentId: "u6",
    country: "Cyprus",
    university: "UCLan Cyprus",
    programme: "BBA",
    intake: "Fall 2026",
    status: "active",
    stages: pipeline(cyprusStages, 4),
    docs: docs(
      ["Academic documents", "Passport copy", "Bank statement", "SWIFT copy"],
      2,
    ),
  },
  {
    id: "s3",
    name: "Mahmudul Hasan",
    email: "mahmudul.hasan3@gmail.com",
    phone: "+880 1713-560927",
    orgId: "ag1",
    counsellorId: "u1",
    agentId: null,
    country: "United Kingdom",
    university: "University of Hertfordshire",
    programme: "MSc Data Science",
    intake: "Fall 2026",
    status: "active",
    stages: pipeline(ukStages, 7),
    docs: docs(
      [
        "Academic documents",
        "IELTS UKVI result",
        "Passport copy",
        "Statement of purpose",
        "TB test certificate",
        "Bank statement",
        "SWIFT copy",
      ],
      6,
    ),
  },
  {
    id: "s4",
    name: "Sadia Islam",
    email: "sadia.islam4@gmail.com",
    phone: "+880 1714-112233",
    orgId: "ag2",
    counsellorId: "u5",
    agentId: null,
    country: "Cyprus",
    university: "Alexander College",
    programme: "Hospitality Management",
    intake: "Fall 2026",
    status: "visa",
    stages: pipeline(cyprusStages, 10),
    docs: docs(
      ["Academic documents", "Passport copy", "Bank statement", "SWIFT copy"],
      4,
    ),
  },
  {
    id: "s5",
    name: "Rakib Hossain",
    email: "rakib.hossain5@gmail.com",
    phone: "+880 1715-445566",
    orgId: "ag1",
    counsellorId: "u3",
    agentId: null,
    country: "Malaysia",
    university: "Taylor's University",
    programme: "BBA",
    intake: "Fall 2026",
    status: "active",
    stages: pipeline(
      [
        "Counselling session",
        "Documents collected",
        "Application submitted",
        "Offer letter received",
        "EMGS approval",
        "VAL issued",
        "Flight booked",
        "Arrived",
      ],
      3,
    ),
    docs: docs(
      [
        "Academic documents",
        "English certificate",
        "Passport copy",
        "Medical screening",
        "SWIFT copy",
      ],
      2,
    ),
  },
  {
    id: "s6",
    name: "Tasnim Ara",
    email: "tasnim.ara6@gmail.com",
    phone: "+880 1716-778899",
    orgId: "ag1",
    counsellorId: "u1",
    agentId: "u6",
    country: "Cyprus",
    university: "Intercollege",
    programme: "BSc Nursing",
    intake: "Spring 2027",
    status: "active",
    stages: pipeline(cyprusStages, 2),
    docs: docs(
      [
        "Academic documents",
        "English certificate",
        "Passport copy",
        "Police clearance",
        "Bank statement",
      ],
      1,
    ),
  },
  {
    id: "s7",
    name: "Imran Kabir",
    email: "imran.kabir7@gmail.com",
    phone: "+880 1717-334455",
    orgId: "ag1",
    counsellorId: "u3",
    agentId: null,
    country: "United Kingdom",
    university: "Coventry University",
    programme: "MBA",
    intake: "Fall 2026",
    status: "refused",
    stages: pipeline(ukStages, 8),
    docs: docs(["Academic documents", "Passport copy", "Bank statement"], 3),
  },
  {
    id: "s8",
    name: "Nafisa Rahman",
    email: "nafisa.rahman8@gmail.com",
    phone: "+880 1718-667788",
    orgId: "ag2",
    counsellorId: "u5",
    agentId: null,
    country: "Canada",
    university: "Conestoga College",
    programme: "Business Administration",
    intake: "Spring 2027",
    status: "active",
    stages: pipeline(
      [
        "Counselling session",
        "IELTS submitted",
        "Application submitted",
        "Letter of acceptance",
        "GIC account",
        "Study permit applied",
        "Biometrics",
        "Permit decision",
        "Arrived",
      ],
      1,
    ),
    docs: docs(
      [
        "Academic documents",
        "IELTS result",
        "Passport copy",
        "GIC certificate",
        "Medical exam",
      ],
      1,
    ),
  },
];

export const payments: Payment[] = [
  {
    id: "p1",
    studentId: "s1",
    title: "Tuition deposit",
    amount: 250000,
    currency: "BDT",
    method: "SWIFT transfer",
    state: "in_review",
    fileName: "swift-ayesha-deposit.pdf",
    submittedAt: day(-1),
    reviewerName: null,
    note: "",
    milestone: "Tuition deposit paid",
  },
  {
    id: "p2",
    studentId: "s2",
    title: "Tuition deposit",
    amount: 180000,
    currency: "BDT",
    method: "Bank cheque",
    state: "pending",
    fileName: null,
    submittedAt: null,
    reviewerName: null,
    note: "",
    milestone: "Tuition deposit paid",
  },
  {
    id: "p3",
    studentId: "s3",
    title: "CAS deposit",
    amount: 320000,
    currency: "BDT",
    method: "SWIFT transfer",
    state: "verified",
    fileName: "swift-mahmudul-cas.pdf",
    submittedAt: day(-12),
    reviewerName: "Nusrat Jahan",
    note: "Amount matches. Funds cleared.",
    milestone: "Unconditional offer and deposit",
  },
  {
    id: "p4",
    studentId: "s6",
    title: "Tuition deposit",
    amount: 150000,
    currency: "BDT",
    method: "Bank transfer",
    state: "rejected",
    fileName: "receipt-tasnim.jpg",
    submittedAt: day(-5),
    reviewerName: "Nusrat Jahan",
    note: "Receipt amount is short by BDT 20,000. Please re-upload.",
    milestone: "Tuition deposit paid",
  },
  {
    id: "p5",
    studentId: "s5",
    title: "Tuition deposit",
    amount: 200000,
    currency: "BDT",
    method: "SWIFT transfer",
    state: "in_review",
    fileName: "swift-rakib.pdf",
    submittedAt: day(0),
    reviewerName: null,
    note: "",
    milestone: "Offer letter received",
  },
];

export const documents: DocumentRecord[] = [
  {
    id: "d1",
    studentId: "s1",
    name: "Police clearance",
    fileName: "police-ayesha.pdf",
    state: "quarantine",
    at: day(0),
  },
  {
    id: "d2",
    studentId: "s1",
    name: "Sponsor letter",
    fileName: "sponsor-ayesha.pdf",
    state: "available",
    at: day(-2),
  },
  {
    id: "d3",
    studentId: "s6",
    name: "English certificate",
    fileName: "ielts-tasnim.pdf",
    state: "scanning",
    at: day(0),
  },
  {
    id: "d4",
    studentId: "s2",
    name: "SWIFT copy",
    fileName: "swift-rafi.pdf",
    state: "available",
    at: day(-4),
  },
  {
    id: "d5",
    studentId: "s8",
    name: "Passport copy",
    fileName: "passport-nafisa.pdf",
    state: "rejected",
    at: day(-3),
  },
];

export const leads: Lead[] = [
  {
    id: "l1",
    name: "Tanjila Haque",
    orgId: "ag1",
    counsellorId: "u1",
    country: "Cyprus",
    university: "UCLan Cyprus",
    programme: "BSc Nursing",
    intake: "Spring 2027",
    status: "contacted",
    createdAt: day(-5),
  },
  {
    id: "l2",
    name: "Rashed Khan",
    orgId: "ag1",
    counsellorId: "u1",
    country: "United Kingdom",
    university: "Coventry University",
    programme: "MBA",
    intake: "Spring 2027",
    status: "qualified",
    createdAt: day(-2),
  },
  {
    id: "l3",
    name: "Mim Akter",
    orgId: "ag1",
    counsellorId: "u3",
    country: "Malaysia",
    university: "Taylor's University",
    programme: "BBA",
    intake: "Fall 2026",
    status: "new",
    createdAt: day(-8),
  },
];

export const auditLog: AuditEntry[] = [
  {
    id: "a1",
    at: day(0),
    actor: "Nusrat Jahan",
    action: "Verified tuition deposit for Ayesha Siddiqua",
    tone: "ok",
  },
  {
    id: "a2",
    at: day(0),
    actor: "Tanvir Ahmed",
    action: "Updated Imran Kabir to Visa refused",
    tone: "bad",
  },
  {
    id: "a3",
    at: day(-1),
    actor: "System",
    action: "Quarantined police clearance for Ayesha Siddiqua",
    tone: "warn",
  },
  {
    id: "a4",
    at: day(-1),
    actor: "Farhana Akter",
    action: "Invited Mehedi Hasan as counsellor (1 seat added)",
    tone: "brand",
  },
  {
    id: "a5",
    at: day(-2),
    actor: "Platform Ops",
    action: "Created agency Sylhet Desk",
    tone: "info",
  },
];
